### ISSUE TITLE
Adding badge as repo information

### ISSUE THREAD

**Issue by dhiemaz** [kitabisa/buroq#4]
Hi there,

Please consider to add badges in the readme as repo information : 
1. Report Card : https://goreportcard.com
2. CI : any CI used ( for example : travis-ci)
3. Technology 
[technology Go](https://img.shields.io/badge/technology-go-blue.svg)
4. Maintainability : Code climate

I also check the repo using go report card : https://goreportcard.com/report/github.com/kitabisa/buroq

the issues found only about linter, good job :+1:

**Comment by ardityawahyu** [comment]
halo mas @dhiemaz , thanks for coming by :)

we'll do the badges and fixing the linter
